[keywords]

A01 = [
    "motor neuron",
    "plasticity",
    "Plastin 3",
    "amyotropic lateral sclerosis",
    "spinal muscular atrophy",
    "mouse model",
    "cellular",
    "molecular",
    "in vivo",
    ]

A02 = [
    "autophagy-endolysosomal",
    "voluntary motor control",
    "cerebellum",
    "basal ganglia",
    "mouse model",
    "AP-2",
    "ATG5",
    ]

A03 = [
    "Purkinje cell",
    "motor learning",
    "plasticity",
    "mouse model",
    "disruptrd cerebellar motor learning",
    "ataxia",
    ]

A04 = [
    "reward",
    "locomotor behaviour",
    "mouse model",
    "ventral tegmental area",
    "lateral hypothalamus",
    "ageing",
    "obesity",
    "optogenetics",
    "calcium imaging",
    "electrophysiological",
    ]

A05 = [
   "locomotor behaviour",
   "fruit fly",
   "neurogenetic",
   "optophysiological",
   "proprioceptive feedback",
   "ascending/descending pathways",
   ]

A06 = [
    "motor cortex",
    "somatosensory cortex",
    "sensory afferents",
    "cerebellum",
    "ataxia",
    "monkey",
    "invasive recordings",
    "reaching tasks",
    ]

A07 = [
    "synaptic lipid",
    "cortical excitability",
    "brain disorders",
    ]

B01 = [
    "mouse model",
    "ion channel mutations",
    "basal ganglia",
    "thalamus",
    "c-Fos expression mapping",
    "in-vivo electrophysiological recordings",
    "fibre photometry",
    "developmental disorders",
    ]

B02 = [
    "motor network maturation",
    "children",
    "adolescents",
    "multi-channel EEG source localisation",
    "transcranial magnetic stimulation",
    "functional MRI",
    "cortical activation",
    "involuntary tic movements",
    ]

B03 = [
    "computational modelling",
    "cortical network connectivity",
    "causality",
    "simulation",
    "neurological disorders",
    "neurobiological",
    "ageing",
]	

B04 = [
    "predictability",
    "uncertainty",
    "computational modelling",
    "functional MRI",
    "simulated lesions",
    ]

B05 = [
    "neurobiological",
    "inter-individual differences",
    "functional MRI",
    "structural MRI",
    "multivariate statistical learning",
    "ageing",
    "ischemic stroke",
    "transfer-learning",
    ]

C01 = [
    "cell biology",
    "systems neuroscience",
    "spontaneous motor recovery",
    "stroke",
    "transcranial direct current stimulation",
    "tDCS",
    "mouse model",
    ]

C03 = [
    "progressive dopamine deficiency",
    "vigorous volitional movements",
    "Parkinson’s disease",
    "structural networks",
    "functional networks",
    "neuroimaging",
    "dynamic network states",
    ]

C04 = [
    "neurodegeneration-induced apraxia",
    "Alzheimer’s disease",
    "tau-pathology",
    "cortical networks",
    "neuropsychological profiling",
    "Cologne apraxia screening",
    "Tau-PET imaging",
    "functional MRI",
    ]

C05 = [
    "functional MRI",
    "simultaneous TMS-EEG",
    "online-TMS interference",
    "premotor cortex",
    "primary motor cortex",
    "stroke",
    "recovery",
    "theta-burst rTMS",
    ]

C06 = [
    "primary sympathetic effectors",
    "task-based fMRI",
    "functional MRI",
    "effective connectivity",
    "humans",
    "pro-dopaminergic treatment",
    "inflammation",
    "major depression",
    ]

C07 = [
    "real-time measurements",
    "preceding urge phenomena",
    "high-density EEG",
    "thalamic local field potentials",
    "impulsive urges to move",
    "deep brain stimulation",
    "structural connectomics",
    "sensorimotor gating",
    ]

INF = [
    "data management",
    "tools",
    "services",
    "training",
    "data analysis",
    "computational modelling",
    "workflows",
    "data access",
    "processing",
    ]

JRG_Gatto = [
    "spinal cord",
    "sensory ganglia",
    "ethologically relevant behaviors",
    "chronic pain",
    "itching",
    "spasticity",
    "neuron population imaging",
    ]

JRG_Valtcheva = [
    "adult-infant interactions",
    "behavioral motifs",
    "mouse model",
    "new mothers",
    "sensory-hormonal-motor coupling",
    "postpartum conditions",
    ]

X01 = [
    "cross-linking",
    "rehabilitation",
    "restoration",
    "mild Traumatic Brain Injury",
    "mild TBI",
    "transcranial direct current stimulation",
    "tDCS",
    ]

X02 = [
    "cross-linking",
    "sleep",
    "depressivity",
    "motor performance",
    "individual performance",
    ]

X03 = [
    "cross-linking",
    "deep brain stimulation",
    "subthalamic nucleus",
    "STN-DBS",
    "gait",
    "falls",
    "Freezing of Gait",
    "Parkinson's disease",
    "Human",
    "Animal",
    ]

X04 = [
    "cross-linking",
    "cortical network modulation",
    "predictive motor control",
    "subthalamic nucleus",
    "deep brain stimulation",
    "functional MRI",
    ]

Z01 = [
    "central office",
    "outreach",
    "coordination",
    "interaction",
    "recruitment",
    ]

Z02 = [
    "behavioural tests",
    "rodents",
    "systems neuroscience tools",
    "optogenetics",
    "calcium imaging",
    "preprocessing",
    "data analysis",
    "data acquisition",
    ]

Z03 = [
    "behavioural tests",
    "humans",
    "structural MRI",
    "functional MRI",
    "preprocessing",
    "data analysis",
    "data acquisition",
    ]
